### ISSUE TITLE
Investigate how to display framework/libraries specific object

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/reps#154]
Since the debugger starts to implement framework/libraries niceties (e.g. collapsed frames), it would be nice to have something on the Reps side.

The first that come to mind is Immutable, which you can't really inspect natively, but we could potentially target other library (React, to display component/element as JSX, Angular, ExtJS for collections, ...)

It would be nice to come up with a nice structure where the library authors could add their own Reps for the different objects they offer.

We could also have some button or prefs to switch from "lib view" to "native" so lib authors or advanced users can still look at the internals.

What do you think of this @jasonLaster ?

**Comment by jasonLaster** [comment]
I think that's a great idea. 

@jbhoosreddy is looking at a preview for react components. I think immutable would be a great one as well. I think this is actually an Object Inspector concern too.

We are doing work inside of the debugger now because it is easier to bootstrap than the client custom formatter option, but I think we should consider that for previews as well.

What I'm thinking is that it would be nice to build some Console/Debugger side previews quickly over the next couple weeks and then do the custom formatter implementation in a bit. We'd have competing approaches and we could see which works best for us.

**Comment by nchevobbe** [comment]
_Re-created in https://github.com/devtools-html/devtools-core/issues/392_
