### ISSUE TITLE
[suggestion] Change the name of the repo to just 'reps'

### ISSUE THREAD

**Issue by sole** [devtools-html/reps#77]
Since it's in the `devtools` organisation, it is a bit repetitive to also have `devtools` on its name.

I have a `devtools` folder on my drive and checked out this project into a folder called `reps`. So its path is `devtools/reps`. The debugger is in `devtools/debugger`, and so on.

What do you think?

**Comment by nchevobbe** [comment]
It seems good to me, let's see what other people think cc @juliandescottes @janodvarko @jasonLaster 

Since we're speaking about names, I wish devtools-html would be firefox-devtools-html or devtools-html-by-firefox, something that would emphasize that the tools are made by a firefox team/mozilla.
Also, a dedicated logo would be super nice (if I'm correct we use the firefox devedition logo, which does not really represent what the tools are)

**Comment by janodvarko** [comment]
I have been also thinking about this and `reps` would work for me.

Does this mean that we would change also packages in devtools-core? They are also using `devtools-` prefix.
https://github.com/devtools-html/devtools-core/tree/master/packages

But, what about NPM registration? I guess it's a bit easier to get free-namespace if we use `devtools-` (or `firefox-devtools-` prefix and in such case it's nice if npm module name corresponds to directory name.

Honza

**Comment by juliandescottes** [comment]
I agree with the general idea of renaming the repository `reps` and keeping the npm package name `devtools-reps`! 

I've been annoyed by the numerous devtools-* folders on my machine :)

**Comment by nchevobbe** [comment]
Done 😃
