### ISSUE TITLE
Tree should support blur events

### ISSUE THREAD

**Issue by roieu** [devtools-html/reps#91]
Tree of elements, like Sources tree in the debugger should be able to support blur to ensure we keep a selected node highlighted but ignoring any arrow navigation (mute onKeyDown/Press/Up events).
This relates to another issue, to support arrow navigation in the scope panel

**Comment by juliandescottes** [comment]
@roieu I think this issue belongs in https://github.com/devtools-html/debugger.html ?

devtools-html/reps is a library used by the debugger to format and display javascript objects.

**Comment by roieu** [comment]
@juliandescottes you are probably right.. it's just source map lead me to the Tree.js dependency which is part of this repo. But again, I probably miss something here.

**Comment by juliandescottes** [comment]
Thanks for pointing that out! 
I have no idea why we have these 2 tree classes in Reps, probably have to be removed. 

If you're looking for the Tree component used by ManagedTree in debugger.html it's probably https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-sham-modules/client/shared/components/tree.js

So the appropriate repo for creating an issue could be https://github.com/devtools-html/devtools-core/

But since your issue description is about debugger.html UX, it might make more sense to open the issue in the debugger.html repo.

**Comment by roieu** [comment]
@juliandescottes thanks for clarifying that.
I'll post a new issue on the debugger.html repo.

**Comment by roieu** [comment]
Opened another issue [https://github.com/devtools-html/debugger.html/issues/2053](debugger.html)
